name: Code Coverage
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx pytest-cov

      - name: Download Models
        shell: bash
        run: |
          chmod +x download_models.sh
          ./download_models.sh

      - name: Run tests and collect coverage
        run: python -m pytest --disable-warnings --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: File-Sense/engine
